"""
prompts.py

Prompt Builder for the Portfolio AI Explanation Engine.

IMPORTANT
---------
The LLM is an explanation layer ONLY.

Random Forest
LSTM
FinBERT
Fusion Engine

have already completed the portfolio analysis.

The LLM MUST NEVER:

- Change BUY/HOLD/SELL recommendations
- Change confidence
- Predict stock prices
- Recommend new stocks
- Recalculate expected returns
- Override deterministic outputs
- Invent evidence

Its ONLY responsibility is to explain the existing analysis
in professional, plain-English suitable for retail investors.
"""

import json
from typing import Dict

# ---------------------------------------------------------
# JSON Contract
# ---------------------------------------------------------

RESPONSE_SCHEMA = {
    "summary": "<one paragraph summarizing the portfolio>",
    "strengths": [
        "<strength 1>",
        "<strength 2>"
    ],
    "risks": [
        "<risk 1>",
        "<risk 2>"
    ],
    "recommendations": [
        "<recommendation 1>",
        "<recommendation 2>"
    ],
    "outlook": "<future outlook>",
    "confidence_note": "<explanation of model agreement>"
}


# ---------------------------------------------------------
# Prompt Builder
# ---------------------------------------------------------

def build_portfolio_prompt(
    analysis: Dict,
) -> str:
    """
    Convert deterministic portfolio analysis into an LLM prompt.

    Parameters
    ----------
    analysis

        Dictionary generated by HistoricalAnalysis/Fusion Engine.

    Returns
    -------
    str
    """

    schema = json.dumps(RESPONSE_SCHEMA, indent=2)

    prompt = f"""
You are the AI Explanation Engine of TradeMind.

You are NOT a financial advisor.

You are NOT allowed to perform investment analysis.

The portfolio has ALREADY been analyzed using:

- Random Forest
- LSTM
- FinBERT
- Fusion Engine

Those models have already produced the final recommendation.

Your ONLY responsibility is to explain the results.

--------------------------------------------------

STRICT RULES

1. NEVER change any recommendation.

2. NEVER change BUY/HOLD/SELL.

3. NEVER change confidence.

4. NEVER predict prices.

5. NEVER recommend additional stocks.

6. NEVER invent facts.

7. NEVER mention data that is not provided.

8. If some information is unavailable,
   explicitly say so.

9. Explain technical concepts in language
   understandable by a retail investor.

--------------------------------------------------

DETERMINISTIC ANALYSIS

{json.dumps(analysis, indent=2)}

--------------------------------------------------

OUTPUT FORMAT

Return ONLY valid JSON.

No markdown.

No explanations.

No code block.

Use EXACTLY this schema.

{schema}

Field Rules

summary
- Explain overall portfolio health.

strengths
- 2 to 5 concise bullet points.
- Mention only positive findings from the analysis.

risks
- 2 to 5 concise bullet points.
- Mention only existing deterministic risks.

recommendations
- Restate deterministic recommendations.
- Do not create new recommendations.

outlook
- Summarize likely portfolio outlook based ONLY on
  deterministic findings.

confidence_note
- Explain why the confidence is high/medium/low
  using model agreement and confidence values.
- Never invent additional reasoning.

Return JSON only.
"""

    return prompt