@echo off
echo Starting TradeMind...
start cmd /k "cd C:\Users\VICTUS\Desktop\Strotax\Enigma_24\TradeMind && C:\Users\VICTUS\Desktop\Strotax\Enigma_24\trademind_env\Scripts\activate.bat && uvicorn backend.main:app --reload --port 8000"
start cmd /k "cd C:\Users\VICTUS\Desktop\Strotax\Enigma_24\TradeMind\frontend && npm start"
echo Both servers starting...