"""
backend/wealth/advisor/opportunity/analyzer.py

TradeMind Opportunity Analysis Engine

This module contains the quantitative opportunity scoring
engine for portfolio analysis.

Responsibilities
----------------
✓ Evaluate portfolio growth opportunities
✓ Calculate diversification opportunities
✓ Measure holding quality
✓ Aggregate AI confidence
✓ Produce OpportunityComponents

This module intentionally contains NO finding generation
or recommendation logic.
"""

from __future__ import annotations

import logging

from backend.wealth.portfolio_analyzer import PortfolioAnalysis

from .config import OpportunityConfig
from .helpers import (
    clamp,
    confidence_percentage,
    expected_return_score,
    portfolio_growth,
    portfolio_quality,
    round_score,
    safe_mean,
    weighted_score,
)
from .models import (
    ConfidenceSummary,
    HoldingOpportunitySummary,
    OpportunityComponents,
)

logger = logging.getLogger(__name__)


class OpportunityAnalyzer:
    """
    Quantitative engine responsible for calculating
    portfolio opportunity scores.

    The analyzer performs deterministic calculations only.
    It does not generate findings or recommendations.
    """

    def __init__(
        self,
        config: OpportunityConfig | None = None,
    ) -> None:

        self._config = config or OpportunityConfig()

    # ==========================================================
    # Public API
    # ==========================================================

    def analyze(
        self,
        analysis: PortfolioAnalysis,
    ) -> OpportunityComponents:
        """
        Calculate the complete portfolio opportunity score.

        Parameters
        ----------
        analysis
            PortfolioAnalysis generated by
            PortfolioAnalyzer.

        Returns
        -------
        OpportunityComponents
        """

        logger.info(
            "Calculating portfolio opportunity score.",
            extra={
                "portfolio_id": analysis.portfolio_id,
            },
        )

        growth = self._growth_component(
            analysis,
        )

        quality = self._quality_component(
            analysis,
        )

        diversification = (
            self._diversification_component(
                analysis,
            )
        )

        confidence = self._confidence_component(
            analysis,
        )

        total = self._overall_score(
            growth=growth,
            quality=quality,
            diversification=diversification,
            confidence=confidence,
        )

        return OpportunityComponents(
            growth_score=growth,
            quality_score=quality,
            diversification_score=diversification,
            confidence_score=confidence,
            total_score=total,
        )

    # ==========================================================
    # Overall Score
    # ==========================================================

    def _overall_score(
        self,
        *,
        growth: float,
        quality: float,
        diversification: float,
        confidence: float,
    ) -> float:
        """
        Calculate the weighted opportunity score.
        """

        score = weighted_score(
            scores={
                "growth": growth,
                "quality": quality,
                "diversification": diversification,
                "confidence": confidence,
            },
            weights=self._config.component_weights,
        )

        return round_score(
            clamp(score),
        )

    # ==========================================================
    # Growth Opportunity
    # ==========================================================

    def _growth_component(
        self,
        analysis: PortfolioAnalysis,
    ) -> float:
        """
        Evaluate expected portfolio growth.

        Returns a normalized score between 0 and 100.
        """

        expected_returns = [
            holding.expected_return
            for holding in analysis.holdings
        ]

        average_return = portfolio_growth(
            expected_returns,
        )

        score = expected_return_score(
            average_return,
            minimum=self._config.minimum_expected_return,
            maximum=self._config.strong_expected_return,
        )

        logger.debug(
            "Growth component calculated.",
            extra={
                "average_return": average_return,
                "growth_score": score,
            },
        )

        return round_score(score)

    # ==========================================================
    # Diversification Opportunity
    # ==========================================================

    def _diversification_component(
        self,
        analysis: PortfolioAnalysis,
    ) -> float:
        """
        Measure opportunity available through
        better diversification.

        Higher opportunity exists when the portfolio
        is less diversified.
        """

        diversification = (
            analysis.diversification.diversification_score
        )

        score = clamp(
            100.0 - diversification,
        )

        logger.debug(
            "Diversification opportunity calculated.",
            extra={
                "current_diversification": diversification,
                "opportunity_score": score,
            },
        )

        return round_score(score)

    # ==========================================================
    # Holding Quality
    # ==========================================================

    def _quality_component(
        self,
        analysis: PortfolioAnalysis,
    ) -> float:
        """
        Evaluate the overall quality of portfolio holdings.
        """

        quality_scores = [
            holding.ai_score
            for holding in analysis.holdings
        ]

        score = portfolio_quality(
            quality_scores,
        )

        logger.debug(
            "Quality component calculated.",
            extra={
                "quality_score": score,
            },
        )

        return round_score(
            clamp(score),
        )

    # ==========================================================
    # Confidence
    # ==========================================================

    def _confidence_component(
        self,
        analysis: PortfolioAnalysis,
    ) -> float:
        """
        Calculate portfolio AI confidence score.
        """

        confidences = [
            holding.confidence
            for holding in analysis.holdings
        ]

        average = safe_mean(
            confidences,
        )

        return confidence_percentage(
            average,
        )

    # ==========================================================
    # Holding Summaries
    # ==========================================================

    def calculate_holding_summary(
        self,
        analysis: PortfolioAnalysis,
    ) -> list[HoldingOpportunitySummary]:
        """
        Produce opportunity summaries for every holding.
        """

        summaries: list[
            HoldingOpportunitySummary
        ] = []

        for holding in analysis.holdings:

            expected_return = holding.expected_return

            confidence = holding.confidence

            quality = holding.ai_score

            current_price = holding.current_price

            target_price = holding.target_price

            upside = (
                0.0
                if current_price <= 0
                else (
                    (
                        target_price
                        - current_price
                    )
                    / current_price
                )
                * 100.0
            )

            score = expected_return_score(
                expected_return,
                minimum=self._config.minimum_expected_return,
                maximum=self._config.strong_expected_return,
            )

            summaries.append(
                HoldingOpportunitySummary(
                    symbol=holding.symbol,
                    score=round_score(score),
                    expected_return=round_score(
                        expected_return,
                    ),
                    confidence=round_score(
                        confidence_percentage(
                            confidence,
                        ),
                    ),
                    upside=round_score(
                        upside,
                    ),
                    quality=round_score(
                        quality,
                    ),
                )
            )

        return summaries

    # ==========================================================
    # Confidence Summary
    # ==========================================================

    def calculate_confidence_summary(
        self,
        analysis: PortfolioAnalysis,
    ) -> ConfidenceSummary:
        """
        Aggregate portfolio confidence statistics.
        """

        confidences = [
            holding.confidence
            for holding in analysis.holdings
        ]

        if not confidences:

            return ConfidenceSummary(
                average=0.0,
                minimum=0.0,
                maximum=0.0,
                high_confidence_count=0,
                low_confidence_count=0,
            )

        average = safe_mean(
            confidences,
        )

        return ConfidenceSummary(
            average=round_score(
                confidence_percentage(
                    average,
                ),
            ),
            minimum=round_score(
                confidence_percentage(
                    min(confidences),
                ),
            ),
            maximum=round_score(
                confidence_percentage(
                    max(confidences),
                ),
            ),
            high_confidence_count=sum(
                c >= self._config.high_confidence
                for c in confidences
            ),
            low_confidence_count=sum(
                c < self._config.minimum_confidence
                for c in confidences
            ),
        )

    # ==========================================================
    # Validation
    # ==========================================================

    def validate_analysis(
        self,
        analysis: PortfolioAnalysis,
    ) -> None:
        """
        Validate PortfolioAnalysis before scoring.
        """

        if analysis is None:
            raise ValueError(
                "PortfolioAnalysis cannot be None."
            )

        if not analysis.holdings:
            raise ValueError(
                "Portfolio contains no holdings."
            )

    # ==========================================================
    # Explainability
    # ==========================================================

    def explain_score(
        self,
        components: OpportunityComponents,
    ) -> dict[str, float]:
        """
        Return a structured explanation of the
        opportunity score.
        """

        return {
            "growth": components.growth_score,
            "quality": components.quality_score,
            "diversification": (
                components.diversification_score
            ),
            "confidence": (
                components.confidence_score
            ),
            "overall": components.total_score,
        }
