"""
backend/wealth/advisor/opportunity/evaluator.py

TradeMind Opportunity Evaluation Orchestrator

Coordinates the complete portfolio opportunity
evaluation workflow.

Responsibilities
----------------
✓ Validate PortfolioAnalysis
✓ Execute OpportunityAnalyzer
✓ Generate opportunity findings
✓ Produce OpportunityEvaluation DTO

This module intentionally contains NO mathematical
scoring logic.
"""

from __future__ import annotations

import logging

from backend.wealth.portfolio_analyzer import PortfolioAnalysis

from ..enums import HealthStatus, RecommendationType
from ..models import AdvisorFinding
from .analyzer import OpportunityAnalyzer
from .config import OpportunityConfig
from .findings import OpportunityFindingGenerator
from .models import (
    FindingContext,
    HoldingOpportunitySummary,
    OpportunityComponents,
    OpportunityEvaluation,
)

logger = logging.getLogger(__name__)


class OpportunityEvaluator:
    """
    High-level orchestration layer for portfolio
    opportunity evaluation.

    Workflow

        PortfolioAnalysis
                │
                ▼
        Validation
                │
                ▼
        OpportunityAnalyzer
                │
                ▼
        OpportunityFindingGenerator
                │
                ▼
        OpportunityEvaluation
    """

    def __init__(
        self,
        config: OpportunityConfig | None = None,
    ) -> None:

        self._config = config or OpportunityConfig()

        self._analyzer = OpportunityAnalyzer(
            self._config,
        )

        self._finding_generator = (
            OpportunityFindingGenerator(
                self._config,
            )
        )

    # ==========================================================
    # Public API
    # ==========================================================

    def evaluate(
        self,
        analysis: PortfolioAnalysis,
    ) -> OpportunityEvaluation:
        """
        Evaluate portfolio opportunities.

        Parameters
        ----------
        analysis
            PortfolioAnalysis generated by
            PortfolioAnalyzer.

        Returns
        -------
        OpportunityEvaluation
        """

        logger.info(
            "Starting portfolio opportunity evaluation.",
            extra={
                "portfolio_id": analysis.portfolio_id,
            },
        )

        self._analyzer.validate_analysis(
            analysis,
        )

        components = (
            self._analyzer.analyze(
                analysis,
            )
        )

        confidence_summary = (
            self._analyzer.calculate_confidence_summary(
                analysis,
            )
        )

        holding_summary = (
            self._analyzer.calculate_holding_summary(
                analysis,
            )
        )

        recommendation = (
            self._determine_recommendation(
                components.total_score,
            )
        )

        context = FindingContext(
            overall_score=components.total_score,
            portfolio_health=analysis.portfolio_health,
            diversification_score=(
                analysis.diversification.diversification_score
            ),
            average_expected_return=(
                self._average_expected_return(
                    holding_summary,
                )
            ),
            confidence=confidence_summary.average,
            health_status=(
                self._determine_health_status(
                    components.total_score,
                )
            ),
            recommendation=recommendation,
        )

        findings = (
            self._finding_generator.generate(
                analysis=analysis,
                context=context,
                holding_summary=holding_summary,
            )
        )

        result = self._build_result(
            components=components,
            context=context,
            holding_summary=holding_summary,
            findings=findings,
        )

        logger.info(
            "Portfolio opportunity evaluation completed.",
            extra={
                "portfolio_id": analysis.portfolio_id,
                "opportunity_score": result.overall_score,
                "finding_count": len(result.findings),
            },
        )

        return result

    # ==========================================================
    # Helpers
    # ==========================================================

    def _average_expected_return(
        self,
        holdings: list[HoldingOpportunitySummary],
    ) -> float:
        """
        Compute the average expected return of
        all holdings.
        """

        if not holdings:
            return 0.0

        return round(
            sum(
                holding.expected_return
                for holding in holdings
            )
            / len(holdings),
            2,
        )

    # ==========================================================
    # Internal Builders
    # ==========================================================

    def _build_result(
        self,
        *,
        components: OpportunityComponents,
        context: FindingContext,
        holding_summary: list[HoldingOpportunitySummary],
        findings: list[AdvisorFinding],
    ) -> OpportunityEvaluation:
        """
        Construct the final OpportunityEvaluation DTO.
        """

        return OpportunityEvaluation(
            overall_score=components.total_score,
            diversification_score=components.diversification_score,
            expected_return=context.average_expected_return,
            confidence=context.confidence,
            recommendation=context.recommendation,
            health_status=context.health_status,
            holding_summary=holding_summary,
            findings=findings,
        )

    def _determine_health_status(
        self,
        score: float,
    ) -> HealthStatus:
        """
        Determine the portfolio opportunity health.
        """

        if score >= self._config.excellent_score:
            return HealthStatus.EXCELLENT

        if score >= self._config.good_score:
            return HealthStatus.GOOD

        if score >= self._config.average_score:
            return HealthStatus.FAIR

        return HealthStatus.POOR

    def _determine_recommendation(
        self,
        score: float,
    ) -> RecommendationType:
        """
        Determine the overall recommendation.
        """

        if score >= self._config.excellent_score:
            return RecommendationType.STRONG_BUY

        if score >= self._config.good_score:
            return RecommendationType.BUY

        if score >= self._config.average_score:
            return RecommendationType.HOLD

        return RecommendationType.REVIEW

    # ==========================================================
    # Convenience APIs
    # ==========================================================

    def explain(
        self,
        analysis: PortfolioAnalysis,
    ) -> dict[str, float]:
        """
        Return a structured explanation of the opportunity score.
        """

        components = self._analyzer.analyze(analysis)
        return self._analyzer.explain_score(components)

    def score(
        self,
        analysis: PortfolioAnalysis,
    ) -> float:
        """
        Return only the overall opportunity score.
        """

        return self.evaluate(
            analysis,
        ).overall_score

    def findings(
        self,
        analysis: PortfolioAnalysis,
    ) -> list[AdvisorFinding]:
        """
        Return only opportunity findings.
        """

        return self.evaluate(
            analysis,
        ).findings

    def recommendation(
        self,
        analysis: PortfolioAnalysis,
    ) -> RecommendationType:
        """
        Return only the investment recommendation.
        """

        return self.evaluate(
            analysis,
        ).recommendation

    def is_healthy(
        self,
        analysis: PortfolioAnalysis,
    ) -> bool:
        """
        Determine whether the portfolio has good opportunity potential.
        """

        evaluation = self.evaluate(
            analysis,
        )

        return evaluation.health_status in {
            HealthStatus.EXCELLENT,
            HealthStatus.GOOD,
        }

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}"
            f"(config={self._config!r})"
        )
