"""
models.py

Pydantic models for the TradeMind AI Scam & Tip Detector.

Purpose
-------
- Centralize API contracts.
- Define request/response schemas.
- Keep business logic out of this file.
"""

from typing import List, Optional, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------
# Request Model
# ---------------------------------------------------------------------

class ScamRequest(BaseModel):
    """
    Incoming request for scam analysis.
    """

    message: str = Field(
        ...,
        min_length=5,
        description="Investment message or tip to analyze."
    )

    stock_symbol: Optional[str] = Field(
        default=None,
        description="Optional NSE/BSE stock symbol."
    )

    source: Optional[
        Literal[
            "whatsapp",
            "telegram",
            "twitter",
            "email",
            "sms",
            "other",
        ]
    ] = Field(
        default="other",
        description="Origin of the message."
    )


# ---------------------------------------------------------------------
# Supporting Models
# ---------------------------------------------------------------------

class RedFlag(BaseModel):
    """
    Individual rule triggered by the Rule Engine.
    """

    name: str
    description: str
    weight: int


class PumpAnalysis(BaseModel):
    """
    Output from the Pump Detector.
    """

    score: int = 0
    confidence: int = 0
    patterns: List[str] = Field(default_factory=list)
    metrics: dict = Field(default_factory=dict)


class URLAnalysis(BaseModel):
    """
    Output from the URL Analyzer.
    """

    score: int = 0
    confidence: int = 0
    urls: List[str] = Field(default_factory=list)
    findings: List[str] = Field(default_factory=list)


class AIExplanation(BaseModel):
    """
    Human-readable explanation generated by the LLM.
    """

    summary: str
    reasoning: List[str]
    recommendation: str

    class Config:
        extra = "forbid"


# ---------------------------------------------------------------------
# Unified Evidence
# ---------------------------------------------------------------------

class ScamEvidence(BaseModel):
    """
    Structured evidence produced by the deterministic pipeline.
    """

    red_flags: List[str] = Field(default_factory=list)

    pump_patterns: List[str] = Field(default_factory=list)

    url_findings: List[str] = Field(default_factory=list)

    sentiment: str = "unavailable"

    sentiment_summary: str = ""

    class Config:
        extra = "forbid"


# ---------------------------------------------------------------------
# Final Response
# ---------------------------------------------------------------------

class ScamResponse(BaseModel):
    """
    Final response returned by the Scam Detector.
    """

    classification: str

    risk_score: int = Field(
        ge=0,
        le=100
    )

    confidence: int = Field(
        ge=0,
        le=100
    )

    recommendation: str

    explanation: AIExplanation

    evidence: ScamEvidence

    available_models: List[str] = Field(default_factory=list)

    models_unavailable: List[str] = Field(default_factory=list)

    class Config:
        extra = "forbid"
